name: Urls checking

on:
  workflow_run:
    workflows: ["Generate CSV and README"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Urlshecker
      uses: urlstechie/urlchecker-action@master
      with:
        git_path: https://github.com/SuperKogito/SER-datasets
        cleanup: true
        file_types: ".md"
        print_all: false
        timeout: 9
        retry_count: 3
        force_pass: true
